--
-- PostgreSQL database dump
--

-- Dumped from database version 11.3
-- Dumped by pg_dump version 11.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

CREATE TABLE public.movies (
    id integer NOT NULL,
    title text,
    release_date date    
);

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;

CREATE TABLE public.actors (
    id integer NOT NULL,
    name text,
    age text,
    gender text    
);

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;

CREATE TABLE public.movies_actors (
    id integer NOT NULL,
    movie_id integer,
    actor_id integer        
);

CREATE SEQUENCE public.movies_actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.movies_actors_id_seq OWNED BY public.movies_actors.id;

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);

ALTER TABLE ONLY public.movies_actors ALTER COLUMN id SET DEFAULT nextval('public.movies_actors_id_seq'::regclass);


COPY public.movies (id, title, release_date) FROM stdin;
1	Miracle in cell 7	"2019/10/08"
2	Changeling	"2008/10/23"
3	The Passenger	"2018/01/08"
4	Indiana Jones and the Kingdom of the Crystal Skull	"2008/05/20"
5	The Bodyguard	"1992/11/25"
\.

COPY public.actors (id, name, age, gender) FROM stdin;
1	Nisa Sofiya Aksongur	9	Female
2	Julie Andrews	85	Female
3	Lynda Carter	69	Female
4	Denzel Washington	66	Male
5	Julia Roberts	53	Female
\.


SELECT pg_catalog.setval('public.movies_id_seq', 5, true);

SELECT pg_catalog.setval('public.actors_id_seq', 5, true);

SELECT pg_catalog.setval('public.movies_actors_id_seq', 1, false);


ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.movies_actors
    ADD CONSTRAINT movies_actors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.movies_actors
    ADD CONSTRAINT movie_id FOREIGN KEY (movie_id) REFERENCES public.movies(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.movies_actors
    ADD CONSTRAINT actor_id FOREIGN KEY (actor_id) REFERENCES public.actors(id) ON UPDATE CASCADE ON DELETE SET NULL;

--
-- PostgreSQL database dump complete
--

